// Generated by CoffeeScript 2.3.0
(function() {
  var errors, maybeThrow, should;

  require("source-map-support").install();

  should = require("should");

  require("should-sinon");

  errors = [];

  process.on("uncaugthException", function(error) {
    return errors.push({
      type: "uncaughtException",
      error
    });
  });

  process.on("unhandledRejection", function(error) {
    return errors.push({
      type: "unhandledRejection",
      error
    });
  });

  maybeThrow = function() {
    var message;
    if (errors.length === 0) {
      return;
    }
    message = errors.map(e(() => {
      return e.stack;
    })).join("\n\n");
    errors.splice(0, errors.length);
    throw new Error(message);
  };

  beforeEach(function() {
    return maybeThrow;
  });

  afterEach(function() {
    return maybeThrow;
  });

}).call(this);
